eureka.client.fetch-registry=true
eureka.instance.preferIpAddress=true
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultzone=http://localhost:8761/eureka
eureka.instance.hostname=localhost
